import Head from 'next/head';

import { Layout } from '../components/Layout/Layout';

const Home = () => (
  <>
    <Head>
      <title>Tracker</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout />
  </>
);

export default Home;
